# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Philip McGrath <philip@philipmcgrath.com>
tabWidth: 4
useTabs: false
bracketSameLine: false
proseWrap: preserve
# TODO: consider `htmlWhitespaceSensitivity: css`
# See: https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting
htmlWhitespaceSensitivity: strict
endOfLine: auto # we have Git manage this
